spring.config.import=optional:file:.env[.properties]
spring.application.name=order-inventory-platform
spring.datasource.url=jdbc:oracle:thin:@//${DB_HOST}:${DB_PORT}/${DB_SERVICE}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.flyway.enabled=true
