CREATE TABLE products (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(200) NOT NULL,
    description VARCHAR2(2000) NULL,
    price NUMBER(12, 2) NOT NULL CHECK(price >= 0),
    category_id NUMBER(19) NOT NULL,
    active NUMBER(1) DEFAULT 1 NOT NULL CHECK (active IN (0,1)),
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE INDEX idx_products_category_id ON products(category_id);