CREATE TABLE orders (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR2(50) NOT NULL CHECK (status IN ('CREATED', 'CANCELLED')),
    customer_name VARCHAR2(200) NOT NULL,
    customer_email VARCHAR2(200) NOT NULL,
    total_amount NUMBER(12, 2) NOT NULL CHECK(total_amount >= 0),
    /* Has to be modified after adding user table issue #11*/
    created_by NUMBER(19),
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL
);