CREATE TABLE order_items (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER(19) NOT NULL,
    product_id NUMBER(19) NOT NULL,
    product_name VARCHAR2(200) NOT NULL,
    quantity NUMBER(10) NOT NULL CHECK(quantity > 0),
    unit_price NUMBER(12, 2) NOT NULL CHECK(unit_price >= 0),
    line_total NUMBER(12, 2) NOT NULL,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE INDEX idx_order_items_order_id ON order_items(order_id);